# Generated by Django 3.2.7 on 2021-10-09 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('BIKE', 'BIKE'), ('CAR', 'CAR'), ('VAN', 'VAN'), ('TRUCK', 'TRUCK')], max_length=255)),
                ('description', models.TextField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('reciever_name', models.CharField(max_length=255)),
                ('reciever_number', models.CharField(max_length=10)),
                ('weight', models.CharField(choices=[('LIGHT', 'LIGHT'), ('MEDIUM', 'MEDIUM'), ('HEAVY', 'HEAVY')], max_length=255)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
