# Generated by Django 3.2.7 on 2021-10-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='vehicle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
